use_frameworks!

platform :ios, '9.0'

# xcodeproj 'ZFFLisaDemo.xcodeproj'

target 'ZFFLisaDemo_Example' do

#target 'ZFFLisaDemo' do
  #pod 'ZFFLisaDemo', :path => '../'

  target 'ZFFLisaDemo_Tests' do
    inherit! :search_paths

    
  end
end
